### ISSUE TITLE
Is it possible to make a button editable ?

### ISSUE THREAD

**Issue by sahanjith** [GetmeUK/ContentEdit#11]
Hello! i want to know like we are changing the content of a <p> tag, can we edit the properties of a button same way ?  Lets say i want to change the background color of a button.  and when i select the button i can change the properties thorough dialog box ?

**Comment by anthonyjb** [comment]
Hi @sahanjith - so at the moment you can only change properties of block level elements so if the anchor tag (that represents your button) resides in a block level element (e.g a paragraph tag) then the only way to change the attributes through the editor is using the code window in the properties dialog and manually applying the classes to the anchor tag.

There's some discussion of possible approaches for button like elements in this issue here: https://github.com/GetmeUK/ContentTools/issues/234 

Hope that's helpful :) Sorry for the late reply I missed this as most issues go against CT and when I had a bunch of issue notification emails come in I only checked there and missed this one :/
