### ISSUE TITLE
Region.setContent adds empty paragraph

### ISSUE THREAD

**Issue by uncaught** [GetmeUK/ContentEdit#15]
When using Region.setContent, all current children are detached, after the last child is detached, an empty p is is added to the dom, afterwards the intended content is added, leaving that empty p in front.

This is a bit problematic because I use Region.setContent when restoring auto-saved content. But the next auto-save would then also save that empty p and when restoring the next time, I have two empty p's and so forth. Not to mention that it is confusing to have an empty p at the top of a region.

**Comment by anthonyjb** [comment]
Hi @uncaught - sounds like the empty regions test is kicking in when it's unwanted - however this is something implemented by the ContentTools EditorApp class and not ContentEdit - so can you confirm you're using ContentTools as well (otherwise I'm looking in the wrong area)?

If this is a CT issue I'll need to address it but in the meantime you would be able to resolve it by disabling this behaviour when calling `Region.setContent`. To do this set the `editor._emptyRegionsAllowed` value to `true` when calling `setContent` and set it back to `false` after.

**Comment by uncaught** [comment]
Ah sorry, I thought this was part of ContentEdit because I landed in the `content-edit.js` file when debugging :)

Thanks for the reply, I had implemented a different work around after noticing that focusing/blurring the empty p removed it again:
```
region.setContent(someContent);
region.children.some((child) => {
  child.focus();
  return !child._domElement.classList.contains('ce-element--empty');
});
```
I think I will keep the focusing of the first child, but your setting is surely a better way of preventing that empty p in the first place!
