### ISSUE TITLE
Can't get it to clone or drag

### ISSUE THREAD

**Issue by ScotsScripts** [GetmeUK/ContentEdit#29]
I added the Enable_drag_cloning line to my js like this:

```var editor;

editor = ContentTools.EditorApp.get();

editor.init(
	'*[data-editable]', 
	'data-name'
);

ContentEdit.ENABLE_DRAG_CLONING = "True";
```

The editor starts up and everything is normal, but nothing happens when I try ALT clicking before getting in an editable area or ALT clicking while in an editable area. How is it supposed to work?

**Comment by anthonyjb** [comment]
@ScotsScripts so sorry if my release notes weren't clear (I've since updated them), the settings should be set like so:

```JavaScript
ContentEdit.ENABLE_DRAG_CLONING = true
```

To clone an element, hold down the alt key then click and hold on an element to begin dragging it. Keep the alt key down while you drag the element to the location you want to clone it to, drop the element and you should get a clone of the element you dragged in the new location, (just to be clear keep the alt key down until you've dropped the element in its new location).  

I've just checked this in the sandbox version included with the repo and so long as you have the latest ContentTools release (1.6.12) this should be working.

**Comment by ScotsScripts** [comment]
I just downloaded the 1.6.12 repo and opened the sandbox index.html file. Drag for images and videos is working fine, but the alt key doesn't create a clone, just drag and drop (I hold the ALT key then click on an image or video and drag it.) I'm using the latest version of Chrome Canary.

**Comment by anthonyjb** [comment]
I'm also using chrome - all I did to test this was open the developers console while viewing the sandbox.html file in the browser, enter `ContentEdit.ENABLE_DRAG_CLONING = true`, hit return and then attempt to drag clone using the alt key and it worked for me.

Can you try this approach please, by default drag/clone isn't enabled in the sandbox demo.

**Comment by ScotsScripts** [comment]
Ok, it worked in the sandbox when I added the js line to the sandbox script.

Can you think of any ways it could work with text blocks in addition to the images/vids that it already works with?

**Comment by anthonyjb** [comment]
it works with every type of element supported by CE, so text, lists tables, etc.

**Comment by ScotsScripts** [comment]
Can you verify that it works on text and other non image/vid elements? For me it starts selecting text, both in the sandbox and in my implementation. The only elements that drag and drop works on for me, clone or not, seems to be images and vids.

**Comment by anthonyjb** [comment]
Yes I was testing on text elements before - with text in CT/CE you need to click and hold for a second before the text becomes draggable - you'll see a helper element when the text is ready to be dragged.

**Comment by ScotsScripts** [comment]
Ah, thanks, that works, I didn't think about holding for a moment. You've been a real help, I appreciate it.

**Comment by anthonyjb** [comment]
no worries - you're not the only person to ask about the text drag behaviour - easy once you know but not immediately obvious :)
